# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Omid Soltan 
tagline:          

author:
  name:           'Omid Soltan'
  url:            None

paginate:         5

# Custom vars
version:          2.1.0

