# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Hyde
tagline:          'A Jekyll theme'

author:
  name:           'Omid Soltan'
  url:            None

paginate:         5

# Custom vars
version:          2.1.0

